// Generated by gencpp from file core_msgs/ball_position_modify.msg
// DO NOT EDIT!


#ifndef CORE_MSGS_MESSAGE_BALL_POSITION_MODIFY_H
#define CORE_MSGS_MESSAGE_BALL_POSITION_MODIFY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace core_msgs
{
template <class ContainerAllocator>
struct ball_position_modify_
{
  typedef ball_position_modify_<ContainerAllocator> Type;

  ball_position_modify_()
    : header()
    , r_size_m(0)
    , b_size_m(0)
    , g_size_m(0)
    , b_img_x_m()
    , b_img_y_m()
    , b_img_z_m()
    , r_img_x_m()
    , r_img_y_m()
    , r_img_z_m()
    , g_img_x_m()
    , g_img_y_m()
    , g_img_z_m()  {
    }
  ball_position_modify_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , r_size_m(0)
    , b_size_m(0)
    , g_size_m(0)
    , b_img_x_m(_alloc)
    , b_img_y_m(_alloc)
    , b_img_z_m(_alloc)
    , r_img_x_m(_alloc)
    , r_img_y_m(_alloc)
    , r_img_z_m(_alloc)
    , g_img_x_m(_alloc)
    , g_img_y_m(_alloc)
    , g_img_z_m(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _r_size_m_type;
  _r_size_m_type r_size_m;

   typedef int32_t _b_size_m_type;
  _b_size_m_type b_size_m;

   typedef int32_t _g_size_m_type;
  _g_size_m_type g_size_m;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _b_img_x_m_type;
  _b_img_x_m_type b_img_x_m;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _b_img_y_m_type;
  _b_img_y_m_type b_img_y_m;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _b_img_z_m_type;
  _b_img_z_m_type b_img_z_m;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _r_img_x_m_type;
  _r_img_x_m_type r_img_x_m;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _r_img_y_m_type;
  _r_img_y_m_type r_img_y_m;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _r_img_z_m_type;
  _r_img_z_m_type r_img_z_m;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _g_img_x_m_type;
  _g_img_x_m_type g_img_x_m;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _g_img_y_m_type;
  _g_img_y_m_type g_img_y_m;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _g_img_z_m_type;
  _g_img_z_m_type g_img_z_m;





  typedef boost::shared_ptr< ::core_msgs::ball_position_modify_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::core_msgs::ball_position_modify_<ContainerAllocator> const> ConstPtr;

}; // struct ball_position_modify_

typedef ::core_msgs::ball_position_modify_<std::allocator<void> > ball_position_modify;

typedef boost::shared_ptr< ::core_msgs::ball_position_modify > ball_position_modifyPtr;
typedef boost::shared_ptr< ::core_msgs::ball_position_modify const> ball_position_modifyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::core_msgs::ball_position_modify_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::core_msgs::ball_position_modify_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace core_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'core_msgs': ['/home/taewook/capstone_1_ROS/src/core_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::core_msgs::ball_position_modify_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::core_msgs::ball_position_modify_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::core_msgs::ball_position_modify_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::core_msgs::ball_position_modify_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::core_msgs::ball_position_modify_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::core_msgs::ball_position_modify_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::core_msgs::ball_position_modify_<ContainerAllocator> >
{
  static const char* value()
  {
    return "490c270e325fa56f68fcb30ddb129e2e";
  }

  static const char* value(const ::core_msgs::ball_position_modify_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x490c270e325fa56fULL;
  static const uint64_t static_value2 = 0x68fcb30ddb129e2eULL;
};

template<class ContainerAllocator>
struct DataType< ::core_msgs::ball_position_modify_<ContainerAllocator> >
{
  static const char* value()
  {
    return "core_msgs/ball_position_modify";
  }

  static const char* value(const ::core_msgs::ball_position_modify_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::core_msgs::ball_position_modify_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 r_size_m\n\
int32 b_size_m\n\
int32 g_size_m\n\
\n\
float32[] b_img_x_m\n\
float32[] b_img_y_m\n\
float32[] b_img_z_m\n\
\n\
float32[] r_img_x_m\n\
float32[] r_img_y_m\n\
float32[] r_img_z_m\n\
\n\
float32[] g_img_x_m\n\
float32[] g_img_y_m\n\
float32[] g_img_z_m\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::core_msgs::ball_position_modify_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::core_msgs::ball_position_modify_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.r_size_m);
      stream.next(m.b_size_m);
      stream.next(m.g_size_m);
      stream.next(m.b_img_x_m);
      stream.next(m.b_img_y_m);
      stream.next(m.b_img_z_m);
      stream.next(m.r_img_x_m);
      stream.next(m.r_img_y_m);
      stream.next(m.r_img_z_m);
      stream.next(m.g_img_x_m);
      stream.next(m.g_img_y_m);
      stream.next(m.g_img_z_m);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ball_position_modify_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::core_msgs::ball_position_modify_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::core_msgs::ball_position_modify_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "r_size_m: ";
    Printer<int32_t>::stream(s, indent + "  ", v.r_size_m);
    s << indent << "b_size_m: ";
    Printer<int32_t>::stream(s, indent + "  ", v.b_size_m);
    s << indent << "g_size_m: ";
    Printer<int32_t>::stream(s, indent + "  ", v.g_size_m);
    s << indent << "b_img_x_m[]" << std::endl;
    for (size_t i = 0; i < v.b_img_x_m.size(); ++i)
    {
      s << indent << "  b_img_x_m[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.b_img_x_m[i]);
    }
    s << indent << "b_img_y_m[]" << std::endl;
    for (size_t i = 0; i < v.b_img_y_m.size(); ++i)
    {
      s << indent << "  b_img_y_m[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.b_img_y_m[i]);
    }
    s << indent << "b_img_z_m[]" << std::endl;
    for (size_t i = 0; i < v.b_img_z_m.size(); ++i)
    {
      s << indent << "  b_img_z_m[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.b_img_z_m[i]);
    }
    s << indent << "r_img_x_m[]" << std::endl;
    for (size_t i = 0; i < v.r_img_x_m.size(); ++i)
    {
      s << indent << "  r_img_x_m[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.r_img_x_m[i]);
    }
    s << indent << "r_img_y_m[]" << std::endl;
    for (size_t i = 0; i < v.r_img_y_m.size(); ++i)
    {
      s << indent << "  r_img_y_m[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.r_img_y_m[i]);
    }
    s << indent << "r_img_z_m[]" << std::endl;
    for (size_t i = 0; i < v.r_img_z_m.size(); ++i)
    {
      s << indent << "  r_img_z_m[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.r_img_z_m[i]);
    }
    s << indent << "g_img_x_m[]" << std::endl;
    for (size_t i = 0; i < v.g_img_x_m.size(); ++i)
    {
      s << indent << "  g_img_x_m[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.g_img_x_m[i]);
    }
    s << indent << "g_img_y_m[]" << std::endl;
    for (size_t i = 0; i < v.g_img_y_m.size(); ++i)
    {
      s << indent << "  g_img_y_m[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.g_img_y_m[i]);
    }
    s << indent << "g_img_z_m[]" << std::endl;
    for (size_t i = 0; i < v.g_img_z_m.size(); ++i)
    {
      s << indent << "  g_img_z_m[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.g_img_z_m[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CORE_MSGS_MESSAGE_BALL_POSITION_MODIFY_H
