(cl:in-package test-msg)
(cl:export '(HEADER-VAL
          HEADER
          SIZE1-VAL
          SIZE1
          IMG_X1-VAL
          IMG_X1
          IMG_Y1-VAL
          IMG_Y1
          DISTANCE1-VAL
          DISTANCE1
          SIZE2-VAL
          SIZE2
          IMG_X2-VAL
          IMG_X2
          IMG_Y2-VAL
          IMG_Y2
          DISTANCE2-VAL
          DISTANCE2
          SIZE3-VAL
          SIZE3
          IMG_X3-VAL
          IMG_X3
          IMG_Y3-VAL
          IMG_Y3
          DISTANCE3-VAL
          DISTANCE3
          SIZE4-VAL
          SIZE4
          IMG_X4-VAL
          IMG_X4
          IMG_Y4-VAL
          IMG_Y4
          MIDPOINT-VAL
          MIDPOINT
          DISTANCE4-VAL
          DISTANCE4
))